# Generated by Django 2.0 on 2017-12-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Classification')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Domain name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Identifier Type',
                'verbose_name_plural': 'Identifier Types',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Watchlist')),
            ],
            options={
                'verbose_name': 'Watch list',
                'verbose_name_plural': 'Watch lists',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silent', models.BooleanField(verbose_name='Silent')),
                ('identifier_value', models.CharField(max_length=255, verbose_name='Identifier Value')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_classification', to='watchlist.Classification')),
                ('identifier_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_identifier_type', to='watchlist.IdentifierType')),
                ('watch_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_watch_list', to='watchlist.Watchlist')),
            ],
            options={
                'verbose_name': 'Watch list Item',
                'verbose_name_plural': 'Watch list Items',
                'ordering': ('-id',),
            },
        ),
    ]
