# Generated by Django 2.0 on 2017-12-19 13:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Data'),
        ),
    ]
